---
title: "SISBID Day 2"
author: "Kim"
date: "July 12, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install packages
```{r, chunk2}
library(devtools)
install_github("jennybc/googlesheets")
library(googlesheets)
```

Read in spreadsheet. You need to make sure it is published to the web (File -> Publish to the web) in order to be able to read it this way.
```{r, chunk3}
sheets_url = "https://docs.google.com/spreadsheets/d/18KQQd4LY5k8Ucux1MvWCsQGQJlvd0ECTnn-3ixdOKFM/pubhtml"
gsurl1 = gs_url(sheets_url)
dat = gs_read(gsurl1)
date_accessed = date()
date_accessed
head(dat)
```
This isn't working?



JSON Section:
Take a look at all of the repos Jeff has on github
```{r, chunk4}
library(jsonlite)
github_url = "https://api.github.com/users/jtleek/repos"
jsonData <- fromJSON(github_url)
dim(jsonData)
jsonData$name
```

Exploring data frame - there's a data frame inside of a data frame, kind of, called "owner"
```{r, chunk5}
table(sapply(jsonData,class))
dim(jsonData$owner)
names(jsonData$owner)
jsonData$owner$html_url
  #Need to subset twice - first the json data set, then the data frame, then the column

```



Web Scraping